name: 部署《后端技术路线》

on:
  push:
    branches:
      - main      # 当main分支更新就触发操作
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE


jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: 安装Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: 构建
        run: |
          cd website
          hugo --minify

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          publish_branch: website
